---
функциональные требования:
  - Пользователь должен иметь возможность создавать онлайн игру
  - Пользователь должен иметь возможность пригласить участника на бой
  - Пользователь должен иметь возможность выбрать язык 
  - Пользователь должен иметь возможность писать в чате
  - Пользователь должен иметь возможность просматривать страницу участников
  - Пользователь должен иметь возможность создавать учетную запись. логин и пароль
нефункциональные требования:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
неявные требования:
  - Сайт должен распологать меню справой стороны
  - Сайт должен распологать чат в нижней части страницы
  - Пользователь должен иметь возможность видеть онлайн игроков
  - Сайт должен распологать информацию ою онлайн игроках в средней части страницы
